In [ ]:

!pip install pulp
from pulp import *
import pandas as pd

Requirement already satisfied: pulp in /usr/local/lib/python3.6/dist-packages (2.3.1)
Requirement already satisfied: amply>=0.1.2 in /usr/local/lib/python3.6/dist-packages (from pulp) (0.1.4)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.6/dist-packages (from amply>=0.1.2->pulp) (2.4.7)
Requirement already satisfied: docutils>=0.3 in /usr/local/lib/python3.6/dist-packages (from amply>=0.1.2->pulp) (0.16)

In [ ]:
dream_teams = pd.DataFrame(columns=['name', 'position', 'GW','predictions',"team","opponent_team","value"])
#Read file of predictions
optimize_df = pd.read_csv("new_optimize_df_to_gw9 (1).csv")
optimize_df = optimize_df.dropna()
optimize_df = optimize_df.drop_duplicates(subset=["name","GW"],keep='first').reset_index()


optimize_df

      index  Unnamed: 0  predictions  ... value  position opponent_team
0         0           0         4.06  ...    45        GK            18
1         1           1         3.65  ...    46        GK            11
2         2           2         3.45  ...    55        GK            19
3         3           3         3.33  ...    45        GK            12
4         4           4         3.14  ...    55        GK             8
...     ...         ...          ...  ...   ...       ...           ...
2951   3220        3220         1.55  ...    62       FWD            15
2952   3221        3221         1.09  ...    57       FWD             5
2953   3222        3222         1.05  ...   103       FWD            17
2954   3223        3223         0.99  ...    58       FWD             1
2955   3224        3224         0.77  ...    58       FWD             6

[2956 rows x 9 columns]

In [ ]:
#Remove 100% sure non-playing players 
pdata9 = optimize_df[optimize_df["GW"]==9]
print(pdata9.shape)
pdata9 = pdata9[pdata9["name"] != "Mohamed Salah"]
print(pdata9.shape)



pdata7 = optimize_df[optimize_df["GW"]==7]
print(pdata7.shape)
pdata7 = pdata7[pdata7["name"] != "Timothy Castagne"]
print(pdata7.shape)


pdata5 = optimize_df[optimize_df["GW"]==5]
print(pdata5.shape)
pdata5 = pdata5[pdata5["name"] != "Kevin De Bruyne"]
pdata5 = pdata5[pdata5["name"] != "Çaglar Söyüncü"]

print(pdata5.shape)

(293, 9)
(292, 9)
(562, 9)
(561, 9)
(539, 9)
(537, 9)

In [ ]:


#Run pip install cell for each GW, or the model crashes.
pdata = optimize_df[optimize_df["GW"]==4]
print(pdata)
pdata = pdata.reset_index()
prob = pulp.LpProblem('FantasyTeam2',LpMaximize)
#Decision variables(x0,x1...xN)
decision_variables = []
for rownum, row in pdata.iterrows():
    variable = str('x' + str(rownum))
    variable = pulp.LpVariable(str(variable), lowBound = 0, upBound = 1, cat= 'Integer') #make variables binary
    decision_variables.append(variable)

print ("Total number of decision_variables: " + str(len(decision_variables)))
# Returns: Total number of decision_variables
#Optimization function
total_points = ""
for rownum, row in pdata.iterrows():
    for i, player in enumerate(decision_variables):
        if rownum == i:
            formula = row['predictions']*player
            total_points += formula
            
prob += total_points
print ("Optimization function: " + str(total_points))
  #Cash constraints
avail_cash = 830
total_paid = ""
for rownum, row in pdata.iterrows():
    for i, player in enumerate(decision_variables):
        if rownum == i:
            formula = row['value']*player
            total_paid += formula

prob += (total_paid <= avail_cash)
  #GK constraint
avail_gk = 1
total_gk = ""
for rownum, row in pdata.iterrows():
    for i, player in enumerate(decision_variables):
        if rownum == i:
            if row['position'] == 'GK':
                formula = 1*player
                total_gk += formula
prob += (total_gk == avail_gk)
#print(total_gk)
avail_def = 3
total_def = ""
for rownum, row in pdata.iterrows():
    for i, player in enumerate(decision_variables):
        if rownum == i:
            if row['position'] == 'DEF':
                formula = 1*player
                total_def += formula
prob += (total_def == avail_def)
#print((total_def))
avail_mid = 4
total_mid = ""
for rownum, row in pdata.iterrows():
    for i, player in enumerate(decision_variables):
        if rownum == i:
            if row['position'] == 'MID':
                formula = 1*player
                total_mid += formula
prob += (total_mid == avail_mid)
#print((total_mid))
avail_fwd = 3
total_fwd = ""
for rownum, row in pdata.iterrows():
    for i, player in enumerate(decision_variables):
        if rownum == i:
            if row['position'] == 'FWD':
                formula = 1*player
                total_fwd += formula
prob += (total_fwd == avail_fwd)
#print(total_fwd)
team_dict= {}
for team in set(pdata.team):
    team_dict[str(team)]=dict()
    team_dict[str(team)]['avail'] = 3
    team_dict[str(team)]['total'] = ""
    for rownum, row in pdata.iterrows():
        for i, player in enumerate(decision_variables):
            if rownum == i:
                if row['team'] == team:
                    formula = 1*player
                    team_dict[str(team)]['total'] += formula

    prob += (team_dict[str(team)]['total'] <= team_dict[str(team)]['avail'])
#print(len(team_dict))
prob.writeLP('FantasyTeam.lp')
optimization_result = prob.solve()
#print("Status:", LpStatus[prob.status])
print("Optimal Solution to the problem: ", value(prob.objective))
variable_name = []
variable_value = []

for v in prob.variables():
    variable_name.append(v.name)
    variable_value.append(v.varValue)

df = pd.DataFrame({'variable': variable_name, 'value': variable_value})
for rownum, row in df.iterrows():
    value = re.findall(r'(\d+)', row['variable'])
    df.loc[rownum, 'variable'] = int(value[0])

df = df.sort_values('variable')

#append results
for rownum, row in pdata.iterrows():
    for results_rownum, results_row in df.iterrows():
        if rownum == results_row['variable']:
            pdata.loc[rownum, 'decision'] = results_row['value']


pdata[pdata.decision==1].predictions.sum() # Returns 2010.8606251232461

pdata[pdata.decision==1].value.sum() # Returns 830
pdata[pdata.decision==1].predictions.sum()

print("Team cost: ",pdata[pdata.decision==1].value.sum())
dream_teams = pd.concat([dream_teams,pdata[pdata.decision==1][["name","GW","predictions","team","opponent_team","position","value"]]])

     index  Unnamed: 0  predictions  ... value  position opponent_team
0        0           0         4.06  ...    45        GK            18
1        1           1         3.65  ...    46        GK            11
2        2           2         3.45  ...    55        GK            19
3        3           3         3.33  ...    45        GK            12
4        4           4         3.14  ...    55        GK             8
..     ...         ...          ...  ...   ...       ...           ...
420    543         543         0.85  ...    55       FWD             9
421    544         544         0.85  ...    55       FWD             9
422    545         545         0.85  ...    49       FWD            16
423    546         546         0.85  ...    49       FWD             7
424    547         547         0.85  ...    49       FWD             7

[425 rows x 9 columns]
Total number of decision_variables: 425
Optimization function: 4.06*x0 + 3.65*x1 + 2.87*x10 + 1.88*x100 + 1.87*x101 + 1.87*x102 + 1.86*x103 + 1.85*x104 + 1.85*x105 + 1.85*x106 + 1.85*x107 + 1.85*x108 + 1.85*x109 + 2.72*x11 + 1.85*x110 + 1.84*x111 + 1.83*x112 + 1.8*x113 + 1.74*x114 + 1.74*x115 + 1.74*x116 + 1.72*x117 + 1.71*x118 + 1.67*x119 + 2.71*x12 + 1.65*x120 + 1.65*x121 + 1.64*x122 + 1.64*x123 + 1.63*x124 + 1.63*x125 + 1.63*x126 + 1.63*x127 + 1.63*x128 + 1.63*x129 + 2.51*x13 + 1.63*x130 + 1.63*x131 + 1.63*x132 + 1.63*x133 + 1.63*x134 + 1.63*x135 + 1.63*x136 + 1.6*x137 + 1.53*x138 + 1.52*x139 + 2.47*x14 + 1.52*x140 + 1.51*x141 + 1.5*x142 + 1.48*x143 + 1.47*x144 + 1.45*x145 + 1.43*x146 + 1.42*x147 + 1.42*x148 + 1.41*x149 + 2.4*x15 + 1.41*x150 + 1.41*x151 + 1.41*x152 + 1.4*x153 + 1.39*x154 + 1.39*x155 + 1.39*x156 + 1.39*x157 + 1.39*x158 + 1.35*x159 + 2.14*x16 + 1.26*x160 + 1.21*x161 + 1.21*x162 + 1.18*x163 + 1.17*x164 + 1.14*x165 + 1.13*x166 + 1.1*x167 + 1.1*x168 + 1.09*x169 + 1.58*x17 + 1.09*x170 + 1.09*x171 + 1.09*x172 + 1.09*x173 + 1.09*x174 + 1.07*x175 + 1.05*x176 + 1.05*x177 + 1.03*x178 + 1.02*x179 + 1.56*x18 + 1.02*x180 + 1.02*x181 + 1.02*x182 + 1.02*x183 + 1.02*x184 + 0.99*x185 + 0.94*x186 + 0.87*x187 + 0.87*x188 + 0.87*x189 + 1.56*x19 + 0.86*x190 + 0.86*x191 + 0.86*x192 + 0.86*x193 + 0.86*x194 + 8.95*x195 + 8.57*x196 + 7.19*x197 + 6.72*x198 + 6.72*x199 + 3.45*x2 + 1.55*x20 + 6.44*x200 + 6.14*x201 + 5.2*x202 + 5.12*x203 + 4.61*x204 + 4.56*x205 + 4.56*x206 + 4.54*x207 + 4.53*x208 + 4.33*x209 + 1.55*x21 + 4.32*x210 + 4.28*x211 + 4.25*x212 + 4.19*x213 + 4.14*x214 + 4.14*x215 + 4.08*x216 + 4.04*x217 + 4.02*x218 + 3.96*x219 + 1.44*x22 + 3.91*x220 + 3.79*x221 + 3.79*x222 + 3.72*x223 + 3.7*x224 + 3.7*x225 + 3.69*x226 + 3.67*x227 + 3.63*x228 + 3.62*x229 + 1.44*x23 + 3.58*x230 + 3.58*x231 + 3.54*x232 + 3.5*x233 + 3.48*x234 + 3.46*x235 + 3.27*x236 + 3.27*x237 + 3.2*x238 + 3.14*x239 + 1.43*x24 + 3.13*x240 + 3.13*x241 + 3.12*x242 + 3.1*x243 + 3.09*x244 + 3.08*x245 + 3.08*x246 + 3.02*x247 + 3.02*x248 + 2.99*x249 + 1.43*x25 + 2.97*x250 + 2.93*x251 + 2.9*x252 + 2.87*x253 + 2.86*x254 + 2.86*x255 + 2.81*x256 + 2.79*x257 + 2.78*x258 + 2.74*x259 + 1.43*x26 + 2.73*x260 + 2.71*x261 + 2.71*x262 + 2.71*x263 + 2.68*x264 + 2.66*x265 + 2.64*x266 + 2.61*x267 + 2.58*x268 + 2.57*x269 + 1.32*x27 + 2.55*x270 + 2.54*x271 + 2.54*x272 + 2.53*x273 + 2.52*x274 + 2.52*x275 + 2.48*x276 + 2.48*x277 + 2.47*x278 + 2.47*x279 + 1.31*x28 + 2.47*x280 + 2.46*x281 + 2.46*x282 + 2.45*x283 + 2.45*x284 + 2.45*x285 + 2.44*x286 + 2.41*x287 + 2.36*x288 + 2.35*x289 + 1.24*x29 + 2.27*x290 + 2.27*x291 + 2.24*x292 + 2.18*x293 + 2.13*x294 + 2.1*x295 + 2.09*x296 + 2.08*x297 + 2.05*x298 + 2.05*x299 + 3.33*x3 + 1.2*x30 + 2.04*x300 + 2.02*x301 + 2.0*x302 + 1.99*x303 + 1.98*x304 + 1.97*x305 + 1.96*x306 + 1.96*x307 + 1.96*x308 + 1.95*x309 + 1.2*x31 + 1.95*x310 + 1.94*x311 + 1.94*x312 + 1.94*x313 + 1.94*x314 + 1.94*x315 + 1.93*x316 + 1.9*x317 + 1.89*x318 + 1.84*x319 + 1.04*x32 + 1.71*x320 + 1.67*x321 + 1.66*x322 + 1.64*x323 + 1.53*x324 + 1.53*x325 + 1.53*x326 + 1.52*x327 + 1.42*x328 + 1.41*x329 + 1.04*x33 + 1.41*x330 + 1.37*x331 + 1.35*x332 + 1.35*x333 + 1.28*x334 + 1.27*x335 + 1.26*x336 + 1.26*x337 + 1.26*x338 + 1.25*x339 + 0.9*x34 + 1.24*x340 + 1.24*x341 + 1.22*x342 + 1.21*x343 + 1.2*x344 + 1.14*x345 + 1.13*x346 + 1.11*x347 + 1.11*x348 + 1.11*x349 + 0.9*x35 + 1.11*x350 + 1.11*x351 + 1.11*x352 + 1.1*x353 + 1.1*x354 + 1.09*x355 + 1.09*x356 + 1.07*x357 + 1.07*x358 + 1.07*x359 + 0.9*x36 + 1.06*x360 + 1.06*x361 + 1.06*x362 + 1.04*x363 + 1.04*x364 + 1.04*x365 + 1.04*x366 + 1.04*x367 + 1.04*x368 + 1.04*x369 + 0.9*x37 + 1.04*x370 + 1.04*x371 + 1.03*x372 + 5.98*x373 + 5.88*x374 + 5.65*x375 + 5.48*x376 + 5.35*x377 + 5.23*x378 + 4.86*x379 + 0.84*x38 + 4.79*x380 + 4.71*x381 + 4.43*x382 + 3.65*x383 + 3.57*x384 + 3.43*x385 + 3.35*x386 + 3.31*x387 + 3.26*x388 + 3.23*x389 + 0.8*x39 + 3.01*x390 + 2.48*x391 + 2.46*x392 + 2.38*x393 + 2.24*x394 + 2.24*x395 + 2.19*x396 + 2.16*x397 + 2.15*x398 + 2.02*x399 + 3.14*x4 + 0.77*x40 + 2.02*x400 + 1.97*x401 + 1.93*x402 + 1.92*x403 + 1.75*x404 + 1.71*x405 + 1.71*x406 + 1.71*x407 + 1.7*x408 + 1.36*x409 + 0.77*x41 + 1.29*x410 + 1.29*x411 + 1.24*x412 + 1.2*x413 + 1.13*x414 + 1.11*x415 + 1.06*x416 + 1.05*x417 + 0.91*x418 + 0.86*x419 + 0.77*x42 + 0.85*x420 + 0.85*x421 + 0.85*x422 + 0.85*x423 + 0.85*x424 + 0.76*x43 + 0.7*x44 + 5.41*x45 + 5.14*x46 + 5.04*x47 + 4.98*x48 + 4.83*x49 + 3.14*x5 + 4.83*x50 + 4.76*x51 + 4.74*x52 + 4.67*x53 + 4.6*x54 + 4.5*x55 + 4.49*x56 + 4.35*x57 + 4.26*x58 + 4.15*x59 + 3.04*x6 + 4.09*x60 + 4.06*x61 + 3.99*x62 + 3.94*x63 + 3.83*x64 + 3.79*x65 + 3.78*x66 + 3.78*x67 + 3.75*x68 + 3.75*x69 + 2.93*x7 + 3.72*x70 + 3.62*x71 + 3.54*x72 + 3.48*x73 + 3.43*x74 + 3.38*x75 + 3.34*x76 + 3.34*x77 + 3.2*x78 + 3.16*x79 + 2.9*x8 + 3.15*x80 + 3.08*x81 + 2.89*x82 + 2.74*x83 + 2.7*x84 + 2.67*x85 + 2.52*x86 + 2.5*x87 + 2.23*x88 + 2.22*x89 + 2.87*x9 + 2.17*x90 + 2.12*x91 + 2.11*x92 + 2.05*x93 + 2.0*x94 + 2.0*x95 + 1.99*x96 + 1.97*x97 + 1.94*x98 + 1.9*x99
Optimal Solution to the problem:  24.25
Team cost:  336

In [ ]:
#Show dream teams

dream_teams

                          name position GW  ...            team opponent_team value
0                Alex McCarthy       GK  4  ...     Southampton            18    45
47               Ryan Bertrand      DEF  4  ...     Southampton            18    50
50          Kyle Walker-Peters      DEF  4  ...     Southampton            18    45
51                 Reece James      DEF  4  ...         Chelsea             6    51
52                  Ben Davies      DEF  4  ...           Spurs            13    49
53                James Justin      DEF  4  ...       Leicester            19    47
195              Heung-Min Son      MID  4  ...           Spurs            13    90
197              Harvey Barnes      MID  4  ...       Leicester            19    71
200              Wilfried Zaha      MID  4  ...  Crystal Palace             5    72
203               Dennis Praet      MID  4  ...       Leicester            19    55
374      Dominic Calvert-Lewin      FWD  4  ...         Everton             3    75
380              Callum Wilson      FWD  4  ...       Newcastle             4    64
382            Patrick Bamford      FWD  4  ...           Leeds            12    58
17              Fraser Forster       GK  4  ...     Southampton            18    40
74              Daniel Amartey      DEF  4  ...       Leicester            19    40
98          Jarrad Branthwaite      DEF  4  ...         Everton             3    40
101                Jake Vokins      DEF  4  ...     Southampton            18    40
260              Dale Stephens      MID  4  ...         Burnley            14    44
267    Ian Carlo Poveda-Ocampo      MID  4  ...           Leeds            12    44
273             Anthony Gordon      MID  4  ...         Everton             3    44
302  Bruno André Cavaco Jordao      MID  4  ...          Wolves             8    44

[21 rows x 7 columns]

In [ ]:
#Save teams for use in website
dream_teams.to_csv('/content/dream_team_df_gw4-9_new.csv')